
/*
        C O L O R S . H  --  c o l o r   d e f i n i t i o n   f i l e
            Mike Dumdei,  6 Holly Lane,  Texarkana TX  75503
*/

#define CO80    3
#define BW80    2
#define MONO    7

#define BLK     0x00
#define BLU     0x01
#define GRN     0x02
#define CYN     0x03
#define RED     0x04
#define MAG     0x05
#define BRN     0x06
#define WHT     0x07
#define GRY     0x08
#define H_BLU   0x09
#define H_GRN   0x0a
#define H_CYN   0x0b
#define H_RED   0x0c
#define H_MAG   0x0d
#define YLW     0x0e
#define H_WHT   0x0f

#define BLK_B   0x00
#define BLU_B   0x10
#define GRN_B   0x20
#define CYN_B   0x30
#define RED_B   0x40
#define MAG_B   0x50
#define BRN_B   0x60
#define WHT_B   0x70

#define BLNK    0x80

#define NRML    0x07
#define INTN    0x0f
#define UNDL    0x01
#define H_UNDL  0x09
#define RVRS    0x70

